-- Staging layer: cleaned, typed tables loaded from Parquet in Day 6.

CREATE TABLE IF NOT EXISTS stg_ad_events (
    id VARCHAR,
    click INTEGER,
    hour BIGINT,
    c1 BIGINT,
    banner_pos INTEGER,
    site_id VARCHAR,
    site_domain VARCHAR,
    site_category VARCHAR,
    app_id VARCHAR,
    app_domain VARCHAR,
    app_category VARCHAR,
    device_id VARCHAR,
    device_ip VARCHAR,
    device_model VARCHAR,
    device_type INTEGER,
    device_conn_type INTEGER,
    c14 DOUBLE,
    c15 DOUBLE,
    c16 DOUBLE,
    c17 DOUBLE,
    c18 DOUBLE,
    c19 DOUBLE,
    c20 DOUBLE,
    c21 DOUBLE,
    event_date DATE,
    event_hour INTEGER,
    flag_unknown_site_id BOOLEAN,
    flag_unknown_site_domain BOOLEAN,
    flag_unknown_site_category BOOLEAN,
    flag_unknown_app_id BOOLEAN,
    flag_unknown_app_domain BOOLEAN,
    flag_unknown_app_category BOOLEAN,
    flag_unknown_device_id BOOLEAN,
    flag_unknown_device_model BOOLEAN,
    flag_unknown_device_type BOOLEAN,
    flag_missing_fields BOOLEAN
);

CREATE TABLE IF NOT EXISTS stg_email_experiment (
    recency INTEGER,
    history_segment VARCHAR,
    history DOUBLE,
    mens INTEGER,
    womens INTEGER,
    zip_code VARCHAR,
    newbie INTEGER,
    channel VARCHAR,
    segment VARCHAR,
    visit INTEGER,
    conversion INTEGER,
    spend DOUBLE,
    treatment_group VARCHAR,
    treatment_label VARCHAR,
    converted INTEGER,
    revenue DOUBLE,
    zip_code_std VARCHAR,
    flag_zip_code_typo BOOLEAN,
    flag_missing_fields BOOLEAN
);
